# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - uni-socialmedia-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: npm install

      - name: Prisma setup
        run: |
          npx prisma migrate deploy
          npx prisma generate

      - name: Build
        run: npm run build

      - name: Copy static files
        run: |
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0AB9C104547D4CDFB090D0BDA4D65CE1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A2DA79A46C4A40BD87D0B8A7B0E1C43C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4B4E04BE74E4BAB8065E55820C37126 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "uni-socialmedia-demo"
          slot-name: "Production"
          package: ./.next/standalone
